site_name: "Florent MICHEL"
theme:
  name: material
  palette:
    # Mode sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Passer au mode clair
  features:
    - navigation.tabs  # Transforme la navigation en onglets en haut
