site_name: "Florent MICHEL"
theme:
  name: material
  palette:
    # Mode clair
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Passer au mode sombre

    # Mode sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Passer au mode clair
  features:
    - navigation.tabs  # Transforme la navigation en onglets en haut
nav:
  - Accueil: index.md
  - Seconde:
    - Suites récurrentes: seconde/suites_recurrentes.md
  - Galois:
    - Introduction: galois/galois1.md
